# Generated by Django 4.0.4 on 2022-05-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('maritalStatus', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependent.employee')),
            ],
        ),
    ]
